FROM python:3.8.0

WORKDIR /opt/be-app

COPY api/ /opt/be-app
EXPOSE 5000
RUN pip install psutil==5.8.0 flask==2.0.2 flask-cors==3.0.1 

CMD ["python", "app.py"]

#CMD ["python", "app.py"]
