version: '3'
services: 
  fe_app:
    build: 
      context: .
      dockerfile: dockerfile-build-fe
    container_name: fe_app
#    ports:
#      - "8080:80"
    networks:
      ra_test_network:
        ipv4_address: 172.30.0.5 

  fe_proxy:
    image: nginx:latest
    container_name: fe_nginx
    ports:
      - "8080:80"
    networks:
      ra_test_network:
        ipv4_address: 172.30.0.10
    volumes:
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf

  be_app:
    build:
      context: .
      dockerfile: dockerfile-build-be 
    container_name: be_app
    command: python app.py
#    ports:
#      - "5000:5000"
    networks:
      ra_test_network:
        ipv4_address: 172.30.0.15

networks:
  ra_test_network:
    name: ra_test_network
    ipam:
      config:
        - subnet: 172.30.0.0/24
